import { SIGTTIN } from "constants";

class ActionTypes {

    static ACTION_LOGIN = "ACTION_LOGIN"
    static ACTION_GET_USER_INFO = "ACTION_GET_USER_INFO"
    static ACTION_LOGOUT = "ACTION_LOGOUT"
    static ACTION_REGISTER = "ACTION_REGISTER"
    static ACTION_GET_CATEGORY = "ACTION_GET_CATEGORY"
    static ACTION_SAVE_INVENTORY = "ACTION_SAVE_INVENTORY"
    static ACTION_GET_INVENTORY_LIST = "ACTION_GET_INVENTORY_LIST"

}

export default ActionTypes;